services:
  api:
    image: evolution-api-api:latest
    restart: always
    env_file:
      - .env
    networks:
      - evolution-net
      - traefik-net
    depends_on:
      - postgres
      - redis
    volumes:
      - evolution_instances:/evolution/instances
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=root_default"
      - "traefik.http.routers.evolution-api.rule=Host(`api.nexwa.online`) || Host(`wa.qwalify.online`)"
      - "traefik.http.routers.evolution-api.entrypoints=websecure"
      - "traefik.http.routers.evolution-api.tls=true"
      - "traefik.http.routers.evolution-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.evolution-api.loadbalancer.server.port=8080"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evolution
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution-net

  redis:
    image: redis:latest
    restart: always
    networks:
      - evolution-net

volumes:
  postgres_data:
  evolution_instances:

networks:
  evolution-net:
    driver: bridge
  traefik-net:
    external: true
    name: root_default
