import type { AIProviderMeta } from './types';

export const AI_PROVIDERS_LIST: AIProviderMeta[] = [
  {
    id: 'gemini',
    name: 'Google Gemini',
    badge: '⚡ Free Tier Available',
    badgeType: 'free',
    description: 'Generous free tier with high rate limits via Google AI Studio. Excellent speed and multilingual reasoning.',
    defaultModel: 'gemini-1.5-flash',
    availableModels: [
      { id: 'gemini-1.5-flash', name: 'Gemini 1.5 Flash (Recommended - Ultra Fast)', tag: 'Free tier' },
      { id: 'gemini-1.5-pro', name: 'Gemini 1.5 Pro (Deep Reasoning)', tag: 'Free tier' },
      { id: 'gemini-2.0-flash-exp', name: 'Gemini 2.0 Flash (Next-gen Experimental)', tag: 'Free tier' },
    ],
    keyGuideUrl: 'https://aistudio.google.com/app/apikey',
    keyGuideSteps: [
      'Go to Google AI Studio (aistudio.google.com/app/apikey).',
      'Sign in with your Google account.',
      'Click "Create API key" and select/create a Google Cloud project.',
      'Copy the key (starts with AIzaSy...) and paste it below. You get 15 RPM for free!',
    ],
    placeholderKey: 'AIzaSy...',
  },
  {
    id: 'groq',
    name: 'Groq',
    badge: '⚡ 100% Free & Blazing Fast',
    badgeType: 'free',
    description: 'Ultra-fast LPU inference engine running open-source models with generous free daily limits.',
    defaultModel: 'llama-3.3-70b-versatile',
    availableModels: [
      { id: 'llama-3.3-70b-versatile', name: 'Llama 3.3 70B (Recommended)', tag: 'Free tier' },
      { id: 'llama-3.1-8b-instant', name: 'Llama 3.1 8B (Sub-100ms)', tag: 'Free tier' },
      { id: 'mixtral-8x7b-32768', name: 'Mixtral 8x7B', tag: 'Free tier' },
    ],
    keyGuideUrl: 'https://console.groq.com/keys',
    keyGuideSteps: [
      'Visit console.groq.com and sign up with GitHub/Google.',
      'Navigate to API Keys in the sidebar.',
      'Click "Create API Key", give it a name (e.g., Qwalify), and copy the key (starts with gsk_...).',
    ],
    placeholderKey: 'gsk_...',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    badge: '⚡ Free & Low-Cost Models',
    badgeType: 'free',
    description: 'Unified API routing to 100+ models from Meta, DeepSeek, Mistral, Google, and OpenAI with free tier access.',
    defaultModel: 'meta-llama/llama-3.3-70b-instruct:free',
    availableModels: [
      { id: 'meta-llama/llama-3.3-70b-instruct:free', name: 'Llama 3.3 70B (Free)', tag: 'Free tier' },
      { id: 'google/gemini-2.0-flash-exp:free', name: 'Gemini 2.0 Flash (Free)', tag: 'Free tier' },
      { id: 'deepseek/deepseek-chat', name: 'DeepSeek V3 (Very Low Cost)' },
      { id: 'anthropic/claude-3.5-sonnet', name: 'Claude 3.5 Sonnet' },
    ],
    keyGuideUrl: 'https://openrouter.ai/keys',
    keyGuideSteps: [
      'Go to openrouter.ai and sign in.',
      'Navigate to Keys (openrouter.ai/keys).',
      'Click "Create Key", copy the key (starts with sk-or-v1-...), and set optional credit limits.',
    ],
    placeholderKey: 'sk-or-v1-...',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    badge: '⭐ Popular Industry Standard',
    badgeType: 'popular',
    description: 'Industry-leading intelligence with GPT-4o and lightweight GPT-4o-mini for reliable structured outputs.',
    defaultModel: 'gpt-4o-mini',
    availableModels: [
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini (Fast & Cost Effective)' },
      { id: 'gpt-4o', name: 'GPT-4o (Omni High Intelligence)' },
      { id: 'gpt-3.5-turbo', name: 'GPT-3.5 Turbo' },
    ],
    keyGuideUrl: 'https://platform.openai.com/api-keys',
    keyGuideSteps: [
      'Log into platform.openai.com.',
      'Navigate to Settings -> API Keys.',
      'Click "Create new secret key", name it "Qwalify", and copy the key (starts with sk-...).',
      'Ensure you have active credits or a payment method attached.',
    ],
    placeholderKey: 'sk-proj-...',
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    badge: '🧠 Best for Conversational Nuance',
    badgeType: 'popular',
    description: 'Claude 3.5 Sonnet and Haiku provide top-tier conversational empathy, qualification nuance, and safety.',
    defaultModel: 'claude-3-5-haiku-20241022',
    availableModels: [
      { id: 'claude-3-5-haiku-20241022', name: 'Claude 3.5 Haiku (Fast & Responsive)' },
      { id: 'claude-3-5-sonnet-20241022', name: 'Claude 3.5 Sonnet (State-of-the-Art)' },
    ],
    keyGuideUrl: 'https://console.anthropic.com/settings/keys',
    keyGuideSteps: [
      'Log into console.anthropic.com.',
      'Navigate to Settings -> API Keys.',
      'Click "Create Key", name it "Qwalify", and copy the key (starts with sk-ant-...).',
    ],
    placeholderKey: 'sk-ant-...',
  },
  {
    id: 'grok',
    name: 'xAI Grok',
    badge: '🚀 High Speed & Directness',
    badgeType: 'fast',
    description: 'Fast, witty, and direct conversational qualification powered by xAI Grok-2.',
    defaultModel: 'grok-2-1212',
    availableModels: [
      { id: 'grok-2-1212', name: 'Grok 2 (Latest)' },
      { id: 'grok-2-mini', name: 'Grok 2 Mini (Fast)' },
    ],
    keyGuideUrl: 'https://console.x.ai/',
    keyGuideSteps: [
      'Sign in to console.x.ai.',
      'Go to API Keys section and create a new key.',
      'Copy the key (starts with xai-...) and paste it below.',
    ],
    placeholderKey: 'xai-...',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'European AI leader offering powerful multilingual models like Mistral Small & Large.',
    defaultModel: 'mistral-small-latest',
    availableModels: [
      { id: 'mistral-small-latest', name: 'Mistral Small (Fast)' },
      { id: 'mistral-large-latest', name: 'Mistral Large (High Accuracy)' },
    ],
    keyGuideUrl: 'https://console.mistral.ai/api-keys/',
    keyGuideSteps: [
      'Visit console.mistral.ai and log in.',
      'Open the API Keys tab and create a new key.',
      'Copy the secret key and paste it below.',
    ],
    placeholderKey: '...',
  },
  {
    id: 'custom',
    name: 'Custom / Local (Ollama / vLLM)',
    description: 'Connect any OpenAI-compatible self-hosted server, local Ollama instance, or proxy endpoint.',
    defaultModel: 'llama3:latest',
    availableModels: [
      { id: 'llama3:latest', name: 'Local Model (Custom name)' },
    ],
    keyGuideUrl: 'https://ollama.com',
    keyGuideSteps: [
      'If using Ollama, ensure it is running with OLLAMA_ORIGINS="*" or via a reverse proxy.',
      'Enter your endpoint URL (e.g., http://localhost:11434/v1 or https://api.yourdomain.com/v1).',
      'Enter an optional bearer token or "ollama" as the key.',
    ],
    placeholderKey: 'Bearer token or custom key',
    requiresCustomEndpoint: true,
  },
];
