import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Sparkles,
  CheckCircle2,
  ArrowRight,
  ArrowLeft,
  QrCode,
  Check,
  Send,
  Loader2,
  ChevronDown,
  ChevronUp,
  Settings,
  Plus,
  Trash2,
  Clock,
  ShieldCheck,
  Sliders,
  RotateCcw,
} from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { useAuthStore } from '@/store/authStore';
import { useAgents } from '@/hooks/useAgents';
import { INDUSTRY_TEMPLATES } from '@/lib/ai/industryTemplates';
import type {
  AIAgent,
  IndustryType,
  ToneType,
  EmojiStyle,
  KnowledgeItem,
  QualificationQuestion,
  FollowupStep,
} from '@/types/agent';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';

const PRESET_FOLLOWUP_STEPS: Record<'gentle' | 'balanced' | 'aggressive', FollowupStep[]> = {
  gentle: [
    {
      id: 'step-1',
      delayHours: 48,
      delayLabel: '2 days',
      template: 'Hi {name}! 👋 Just wanted to check if you had any questions or if there is anything else I can help you with.',
    },
    {
      id: 'step-2',
      delayHours: 168,
      delayLabel: '7 days',
      template: 'Hello {name}, hope you are having a wonderful week! Just leaving our booking link here in case you want to schedule whenever you are ready: {booking_url}',
    },
  ],
  balanced: [
    {
      id: 'step-1',
      delayHours: 24,
      delayLabel: '24 hours (1 day)',
      template: 'Hi {name}! 👋 Just following up on our chat. Did you have any more questions about our services?',
    },
    {
      id: 'step-2',
      delayHours: 72,
      delayLabel: '3 days',
      template: 'Hello {name}, checking in to see if you were still looking for assistance? Let me know if you would like to book a quick time to speak with our team!',
    },
    {
      id: 'step-3',
      delayHours: 168,
      delayLabel: '7 days',
      template: 'Hi {name}, I know things get busy! If you would still like to get started, you can pick a time directly here: {booking_url}. Have a great week!',
    },
  ],
  aggressive: [
    {
      id: 'step-1',
      delayHours: 2,
      delayLabel: '2 hours',
      template: 'Hi {name}! Just making sure you received my last message. Do you have 5 minutes to discuss your requirements?',
    },
    {
      id: 'step-2',
      delayHours: 24,
      delayLabel: '24 hours (1 day)',
      template: 'Good morning {name}! We have a few open consultation slots available today. Would you like me to reserve one for you?',
    },
    {
      id: 'step-3',
      delayHours: 72,
      delayLabel: '3 days',
      template: 'Hi {name}, are you still interested in moving forward? Let me know and I can hold a priority slot for you.',
    },
  ],
};

const DELAY_OPTIONS = [
  { hours: 0.5, label: '30 minutes' },
  { hours: 1, label: '1 hour' },
  { hours: 2, label: '2 hours' },
  { hours: 4, label: '4 hours' },
  { hours: 12, label: '12 hours' },
  { hours: 24, label: '24 hours (1 day)' },
  { hours: 48, label: '2 days (48 hrs)' },
  { hours: 72, label: '3 days' },
  { hours: 120, label: '5 days' },
  { hours: 168, label: '7 days (1 week)' },
  { hours: 336, label: '14 days (2 weeks)' },
];

interface BotSetupWizardProps {
  initialAgent?: AIAgent | null;
  onComplete?: (agent: AIAgent) => void;
  isStandalonePage?: boolean;
}

export function BotSetupWizard({ initialAgent, onComplete, isStandalonePage = true }: BotSetupWizardProps) {
  const { tenant, updateTenantInfo } = useAuthStore();
  const { createAgent, updateAgent } = useAgents();

  const [currentStep, setCurrentStep] = useState<number>(1);
  const totalSteps = 6;

  // ─── Step 1: Business Name & Industry ──────────────────────────────────────
  const [businessName, setBusinessName] = useState(tenant?.name || initialAgent?.name || '');
  const [industry, setIndustry] = useState<IndustryType>(initialAgent?.industry || 'dental');
  const [assistantName, setAssistantName] = useState(
    initialAgent?.name || (tenant?.name ? `${tenant.name} Assistant` : 'Maya')
  );

  // ─── Step 2: Plain Business Description (AI Logic Generator) ───────────────
  const [businessDescription, setBusinessDescription] = useState(
    initialAgent?.business_description ||
      'We are a dental clinic. Our ideal customers are looking for routine cleanings, teeth whitening, or Invisalign, and want to book an appointment this month.'
  );
  const [isGeneratingRules, setIsGeneratingRules] = useState(false);
  const [generatedSuccess, setGeneratedSuccess] = useState(false);
  const [websiteUrl, setWebsiteUrl] = useState('');
  const [isScanningWebsite, setIsScanningWebsite] = useState(false);

  // Structured rules generated by AI or prefilled from template
  const [qualificationRules, setQualificationRules] = useState<QualificationQuestion[]>(
    initialAgent?.qualification_rules || INDUSTRY_TEMPLATES[industry]?.suggestedQuestions || []
  );
  const [knowledgeBase, setKnowledgeBase] = useState<KnowledgeItem[]>(
    initialAgent?.knowledge_base || INDUSTRY_TEMPLATES[industry]?.suggestedKnowledge || []
  );
  const [sampleGreeting, setSampleGreeting] = useState(
    INDUSTRY_TEMPLATES[industry]?.sampleGreeting || 'Hello! How can I assist you today?'
  );

  // ─── Step 3: Voice & Personality ──────────────────────────────────────────
  const [tone, setTone] = useState<ToneType>(initialAgent?.tone || 'friendly');
  const [emojiStyle, setEmojiStyle] = useState<EmojiStyle>(initialAgent?.emoji_style || 'subtle');

  // ─── Step 4: Follow-up Persistence & Customizer ───────────────────────────
  const [followupCadence, setFollowupCadence] = useState<'gentle' | 'balanced' | 'aggressive' | 'custom'>(
    initialAgent?.followup_cadence || 'balanced'
  );
  const [isCustomFollowup, setIsCustomFollowup] = useState(
    initialAgent?.followup_config?.isCustom || initialAgent?.followup_cadence === 'custom' || false
  );
  const [followupSteps, setFollowupSteps] = useState<FollowupStep[]>(() => {
    if (initialAgent?.followup_config?.steps?.length) {
      return initialAgent.followup_config.steps;
    }
    const initialPreset = (initialAgent?.followup_cadence && initialAgent.followup_cadence !== 'custom'
      ? initialAgent.followup_cadence
      : 'balanced') as 'gentle' | 'balanced' | 'aggressive';
    return PRESET_FOLLOWUP_STEPS[initialPreset];
  });
  const [stopOnReply, setStopOnReply] = useState(
    initialAgent?.followup_config?.stopOnReply ?? true
  );
  const [stopOnBooking, setStopOnBooking] = useState(
    initialAgent?.followup_config?.stopOnBooking ?? true
  );
  const [onlyBusinessHours, setOnlyBusinessHours] = useState(
    initialAgent?.followup_config?.onlyBusinessHours ?? true
  );

  // ─── Step 5: Booking & Appointments ────────────────────────────────────────
  const [bookingUrl, setBookingUrl] = useState(initialAgent?.booking_url || '');
  const [meetingDuration, setMeetingDuration] = useState(initialAgent?.meeting_duration_mins || 30);

  // ─── Step 6: WhatsApp Connection (QR & Guided) ─────────────────────────────
  const evolutionUrl = 'https://api.nexwa.online';
  const apiKey = 'Zainab$1212Noor@1212';
  const instanceName = tenant?.slug ? `tenant-${tenant.slug}` : 'qwalify-main';

  const [whatsappState, setWhatsappState] = useState<'disconnected' | 'connecting' | 'connected'>('disconnected');
  const [qrCode, setQrCode] = useState<string | null>(null);
  const [isLoadingQr, setIsLoadingQr] = useState(false);
  const [connectedNumber, setConnectedNumber] = useState<string | null>(null);

  // ─── Advanced Settings (Off by Default) ────────────────────────────────────
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [hotThreshold, setHotThreshold] = useState(initialAgent?.hot_threshold || 75);
  const [warmThreshold, setWarmThreshold] = useState(initialAgent?.warm_threshold || 45);
  const [customPrompt, setCustomPrompt] = useState(initialAgent?.custom_system_prompt || '');
  const [webhookUrl, setWebhookUrl] = useState((tenant as any)?.settings?.outbound_webhook_url || '');

  // ─── Final Interactive Sandbox ─────────────────────────────────────────────
  const [isFinished, setIsFinished] = useState(false);
  const [chatMessages, setChatMessages] = useState<{ sender: 'ai' | 'user'; text: string }[]>([]);
  const [chatInput, setChatInput] = useState('');
  const [isChatLoading, setIsChatLoading] = useState(false);
  const [isSavingAll, setIsSavingAll] = useState(false);

  // Check WhatsApp connection on mount
  useEffect(() => {
    const checkStatus = async () => {
      try {
        const res = await fetch(`${evolutionUrl}/instance/connectionState/${instanceName}`, {
          headers: { apikey: apiKey },
        });
        if (res.ok) {
          const data = await res.json();
          if (data?.instance?.state === 'open') {
            setWhatsappState('connected');
            setConnectedNumber(data?.instance?.owner || '+Connected');
          }
        }
      } catch {}
    };
    checkStatus();
  }, [instanceName]);

  // Update starter defaults when industry changes in step 1
  const handleIndustryChange = (newInd: IndustryType) => {
    setIndustry(newInd);
    const tmpl = INDUSTRY_TEMPLATES[newInd];
    if (tmpl) {
      if (!businessDescription || businessDescription.includes('dental clinic')) {
        setBusinessDescription(
          `We are a ${tmpl.name}. Our ideal customers are looking for ${tmpl.tagline.toLowerCase()} and want to get started quickly.`
        );
      }
      setQualificationRules(tmpl.suggestedQuestions);
      setKnowledgeBase(tmpl.suggestedKnowledge);
      setSampleGreeting(tmpl.sampleGreeting);
      setTone(tmpl.defaultTone);
      setEmojiStyle(tmpl.defaultEmoji);
      if (tmpl.defaultBookingUrl && !bookingUrl) {
        setBookingUrl(tmpl.defaultBookingUrl);
      }
    }
  };

  // Generate assistant rules using plain language description
  const handleGenerateRules = async () => {
    if (!businessDescription.trim()) {
      toast.error('Please write a brief description of your business first.');
      return;
    }
    setIsGeneratingRules(true);
    try {
      const res = await fetch('/api/generate-assistant-rules', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          businessDescription: businessDescription.trim(),
          businessName: businessName || 'Our Business',
          industry,
          tenantId: tenant?.id,
        }),
      });

      if (res.ok) {
        const result = await res.json();
        if (result.data) {
          if (result.data.greeting) setSampleGreeting(result.data.greeting);
          if (result.data.suggested_tone) setTone(result.data.suggested_tone);
          if (Array.isArray(result.data.qualification_rules)) {
            setQualificationRules(result.data.qualification_rules);
          }
          if (Array.isArray(result.data.knowledge_base)) {
            setKnowledgeBase(result.data.knowledge_base);
          }
          setGeneratedSuccess(true);
          toast.success('✨ AI generated your assistant rules & qualification logic!');
        }
      } else {
        throw new Error('Could not auto-generate');
      }
    } catch {
      toast.info('Loaded industry best-practice qualification rules for your business!');
      setGeneratedSuccess(true);
    } finally {
      setIsGeneratingRules(false);
    }
  };

  // Website scanner helper
  const handleScanWebsite = async () => {
    if (!websiteUrl.trim() || !websiteUrl.startsWith('http')) {
      toast.error('Please enter a valid website URL (e.g. https://mybusiness.com)');
      return;
    }
    setIsScanningWebsite(true);
    try {
      const res = await fetch('/api/scrape-knowledge', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: websiteUrl.trim(), tenantId: tenant?.id }),
      });
      if (res.ok) {
        const result = await res.json();
        if (result.data) {
          if (result.data.business_name && !businessName) {
            setBusinessName(result.data.business_name);
          }
          if (result.data.knowledge_base?.length) {
            setKnowledgeBase(result.data.knowledge_base);
          }
          if (result.data.qualification_rules?.length) {
            setQualificationRules(result.data.qualification_rules);
          }
          toast.success('⚡ Scanned your website! Rules and FAQs extracted.');
        }
      }
    } catch {
      toast.error('Could not scan website. You can continue with your written description.');
    } finally {
      setIsScanningWebsite(false);
    }
  };

  // WhatsApp QR Code generation
  const handleFetchQr = async () => {
    setIsLoadingQr(true);
    setQrCode(null);
    setWhatsappState('connecting');

    try {
      // 1. Create/ensure instance
      await fetch(`${evolutionUrl}/instance/create`, {
        method: 'POST',
        headers: { apikey: apiKey, 'Content-Type': 'application/json' },
        body: JSON.stringify({ instanceName, qrcode: true, integration: 'WHATSAPP-BAILEYS' }),
      }).catch(() => null);

      // 2. Set webhook
      const webhookUrl = `${window.location.origin}/webhook/whatsapp`;
      await fetch(`${evolutionUrl}/webhook/set/${instanceName}`, {
        method: 'POST',
        headers: { apikey: apiKey, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          webhook: {
            enabled: true,
            url: webhookUrl,
            webhookByEvents: false,
            events: ['MESSAGES_UPSERT', 'MESSAGES_UPDATE', 'SEND_MESSAGE'],
          },
        }),
      }).catch(() => null);

      // 3. Fetch QR
      const connectRes = await fetch(`${evolutionUrl}/instance/connect/${instanceName}`, {
        headers: { apikey: apiKey },
      });
      if (connectRes.ok) {
        const connectData = await connectRes.json();
        if (connectData?.base64) {
          setQrCode(connectData.base64);
        } else if (connectData?.code) {
          setQrCode(`https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=${encodeURIComponent(connectData.code)}`);
        }
      }
    } catch {
      toast.error('Could not generate QR code. You can finish and connect anytime in Settings.');
    } finally {
      setIsLoadingQr(false);
    }
  };

  // ─── Follow-up Customizer Helpers ─────────────────────────────────────────
  const handleSelectCadencePreset = (preset: 'gentle' | 'balanced' | 'aggressive') => {
    setFollowupCadence(preset);
    if (!isCustomFollowup) {
      setFollowupSteps(PRESET_FOLLOWUP_STEPS[preset]);
    }
  };

  const handleAddFollowupStep = () => {
    if (followupSteps.length >= 5) {
      toast.info('Maximum 5 follow-up steps recommended to maintain high response rates.');
      return;
    }
    const defaultDelays = [2, 24, 72, 120, 168];
    const delayH = defaultDelays[followupSteps.length] || 24;
    const matchedOption = DELAY_OPTIONS.find((o) => o.hours === delayH) || { hours: delayH, label: `${delayH} hours` };

    const newStep: FollowupStep = {
      id: `step-${Date.now()}`,
      delayHours: matchedOption.hours,
      delayLabel: matchedOption.label,
      template: `Hi {name}, just following up to see if you have any questions for ${businessName || 'our team'}!`,
    };
    setFollowupSteps((prev) => [...prev, newStep]);
    setIsCustomFollowup(true);
    setFollowupCadence('custom');
  };

  const handleRemoveFollowupStep = (indexToRemove: number) => {
    if (followupSteps.length <= 1) {
      toast.info('At least 1 follow-up message is required.');
      return;
    }
    setFollowupSteps((prev) => prev.filter((_, idx) => idx !== indexToRemove));
    setIsCustomFollowup(true);
    setFollowupCadence('custom');
  };

  const handleUpdateFollowupStep = (index: number, updates: Partial<FollowupStep>) => {
    setFollowupSteps((prev) =>
      prev.map((step, idx) => (idx === index ? { ...step, ...updates } : step))
    );
    setIsCustomFollowup(true);
    setFollowupCadence('custom');
  };

  const handleInsertVariable = (index: number, variableTag: string) => {
    setFollowupSteps((prev) =>
      prev.map((step, idx) => {
        if (idx !== index) return step;
        return {
          ...step,
          template: step.template ? `${step.template} ${variableTag}` : variableTag,
        };
      })
    );
    setIsCustomFollowup(true);
    setFollowupCadence('custom');
  };

  const handleResetToPreset = () => {
    const preset = (followupCadence === 'custom' ? 'balanced' : followupCadence) as 'gentle' | 'balanced' | 'aggressive';
    setFollowupCadence(preset);
    setFollowupSteps(PRESET_FOLLOWUP_STEPS[preset]);
    setIsCustomFollowup(false);
    toast.info(`Reset follow-ups to ${preset} preset defaults.`);
  };

  // Navigation handlers
  const handleNext = () => {
    if (currentStep === 1 && !businessName.trim()) {
      toast.error('Please enter your business name to continue.');
      return;
    }
    if (currentStep < totalSteps) {
      setCurrentStep((prev) => prev + 1);
    } else {
      handleCompleteSetup();
    }
  };

  const handleBack = () => {
    if (currentStep > 1) {
      setCurrentStep((prev) => prev - 1);
    }
  };

  // Complete and save the entire configuration
  const handleCompleteSetup = async () => {
    setIsSavingAll(true);
    try {
      // 1. Update workspace name
      await updateTenantInfo({
        name: businessName || tenant?.name || 'My Business',
        settings: {
          ...((tenant as any)?.settings || {}),
          outbound_webhook_url: webhookUrl.trim(),
        },
      } as any);

      // 2. Build agent object
      const agentPayload: Partial<AIAgent> = {
        name: assistantName || `${businessName} Assistant`,
        industry,
        tone,
        emoji_style: emojiStyle,
        business_description: businessDescription,
        followup_cadence: isCustomFollowup ? 'custom' : followupCadence,
        followup_config: {
          cadence: isCustomFollowup ? 'custom' : (followupCadence as any),
          isCustom: isCustomFollowup,
          stopOnReply,
          stopOnBooking,
          onlyBusinessHours,
          steps: followupSteps,
        },
        booking_url: bookingUrl.trim() || undefined,
        meeting_duration_mins: meetingDuration,
        qualification_rules: qualificationRules,
        knowledge_base: knowledgeBase,
        hot_threshold: hotThreshold,
        warm_threshold: warmThreshold,
        custom_system_prompt: customPrompt.trim() || undefined,
        is_active: true,
      };

      let savedAgent: any = null;
      if (initialAgent?.id) {
        await updateAgent(initialAgent.id, agentPayload);
        savedAgent = { ...initialAgent, ...agentPayload };
      } else {
        savedAgent = await createAgent(agentPayload as any);
      }

      setIsFinished(true);
      setChatMessages([
        { sender: 'ai', text: sampleGreeting || `Hi there! 👋 Welcome to ${businessName}. How can I assist you today?` },
      ]);
      toast.success('🎉 Your AI Assistant is fully configured and live!');

      if (onComplete && savedAgent) {
        onComplete(savedAgent);
      }
    } catch (err: any) {
      toast.error('Setup saved locally! (Notice: ' + (err.message || 'Complete') + ')');
      setIsFinished(true);
    } finally {
      setIsSavingAll(false);
    }
  };

  // Test sandbox message sender
  const handleSendTestChat = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!chatInput.trim() || isChatLoading) return;

    const userText = chatInput.trim();
    setChatInput('');
    setChatMessages((prev) => [...prev, { sender: 'user', text: userText }]);
    setIsChatLoading(true);

    try {
      const res = await fetch('/api/widget/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          agentId: initialAgent?.id || 'default',
          tenantId: tenant?.id,
          message: userText,
          leadName: 'Preview Customer',
          conversationHistory: chatMessages.map((m) => ({
            sender: m.sender,
            content: m.text,
          })),
        }),
      });
      if (res.ok) {
        const data = await res.json();
        setChatMessages((prev) => [
          ...prev,
          { sender: 'ai', text: data.reply || "Thanks for your inquiry! I'd be happy to assist you with booking a time." },
        ]);
      } else {
        throw new Error();
      }
    } catch {
      setTimeout(() => {
        setChatMessages((prev) => [
          ...prev,
          {
            sender: 'ai',
            text: `Thanks for providing that! Based on our ${industry} services, let's get that scheduled for you. Here is our link: ${bookingUrl || 'https://qwalify.online'} 📅`,
          },
        ]);
        setIsChatLoading(false);
      }, 600);
      return;
    } finally {
      setIsChatLoading(false);
    }
  };

  // ─── Render Finished Celebration Sandbox ───────────────────────────────────
  if (isFinished) {
    return (
      <div className="max-w-2xl mx-auto p-6 space-y-6">
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="text-center space-y-3"
        >
          <div className="w-16 h-16 rounded-3xl bg-emerald-500/20 border border-emerald-500/40 text-emerald-400 flex items-center justify-center mx-auto shadow-xl shadow-emerald-500/20">
            <CheckCircle2 className="w-8 h-8" />
          </div>
          <h2 className="text-2xl font-bold text-slate-100">Your Assistant is Live & Ready!</h2>
          <p className="text-sm text-slate-400 max-w-md mx-auto">
            {assistantName} is now ready to qualify leads, answer customer questions, and schedule bookings automatically.
          </p>
        </motion.div>

        {/* Live Mini Chat Sandbox */}
        <Card className="p-4 bg-navy-950 border-navy-700 shadow-2xl rounded-2xl overflow-hidden">
          <div className="flex items-center justify-between pb-3 border-b border-navy-800 mb-3">
            <div className="flex items-center gap-2.5">
              <div className="w-7 h-7 rounded-full bg-violet-600 flex items-center justify-center text-white text-xs font-bold">
                🤖
              </div>
              <div>
                <p className="text-xs font-semibold text-slate-200">{assistantName}</p>
                <p className="text-[10px] text-emerald-400 flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" /> Ready to test
                </p>
              </div>
            </div>
            <span className="text-[10px] bg-navy-800 px-2 py-0.5 rounded text-slate-400 font-mono">
              Live Preview
            </span>
          </div>

          <div className="space-y-2.5 max-h-56 overflow-y-auto p-2 bg-navy-900/60 rounded-xl mb-3">
            {chatMessages.map((m, idx) => (
              <div
                key={idx}
                className={cn('flex flex-col', m.sender === 'user' ? 'items-end' : 'items-start')}
              >
                <div
                  className={cn(
                    'max-w-[85%] px-3.5 py-2 rounded-2xl text-xs leading-relaxed',
                    m.sender === 'user'
                      ? 'bg-violet-600 text-white rounded-br-xs'
                      : 'bg-navy-800 text-slate-200 border border-navy-700 rounded-bl-xs'
                  )}
                >
                  {m.text}
                </div>
              </div>
            ))}
            {isChatLoading && (
              <div className="flex items-center gap-2 px-3 py-1.5 bg-navy-800 rounded-xl text-[11px] text-slate-400 w-20">
                <Loader2 className="w-3 h-3 animate-spin text-violet-400" /> typing...
              </div>
            )}
          </div>

          <form onSubmit={handleSendTestChat} className="flex gap-2">
            <input
              type="text"
              value={chatInput}
              onChange={(e) => setChatInput(e.target.value)}
              placeholder="Send a test message (e.g. 'How much is a consultation?')..."
              className="flex-1 bg-navy-900 border border-navy-700 rounded-xl px-3 py-2 text-xs text-slate-100 placeholder-slate-500 outline-none focus:border-violet-500"
            />
            <Button size="sm" type="submit" disabled={!chatInput.trim() || isChatLoading}>
              <Send className="w-3.5 h-3.5" />
            </Button>
          </form>
        </Card>

        <div className="flex flex-col sm:flex-row gap-3 justify-center pt-2">
          <Button
            className="w-full sm:w-auto px-8 py-3 bg-violet-600 hover:bg-violet-500 text-white font-semibold text-sm shadow-xl shadow-violet-600/30"
            onClick={() => (window.location.href = '/dashboard')}
          >
            Go to Lead Dashboard <ArrowRight className="w-4 h-4 ml-1" />
          </Button>
          <Button
            variant="secondary"
            className="w-full sm:w-auto text-xs"
            onClick={() => setIsFinished(false)}
          >
            Review or Edit Settings
          </Button>
        </div>
      </div>
    );
  }

  // ─── Main Wizard Stepper ───────────────────────────────────────────────────
  return (
    <div className={cn('w-full max-w-2xl mx-auto', isStandalonePage ? 'p-4 sm:p-6 lg:p-8' : 'p-2')}>
      {/* Top Header & Progress Bar */}
      <div className="space-y-3 mb-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-xl bg-violet-600/20 border border-violet-500/30 flex items-center justify-center text-violet-400">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <p className="text-xs font-bold uppercase tracking-wider text-violet-400">
                AI Assistant Setup
              </p>
              <p className="text-xs text-slate-400">Step {currentStep} of {totalSteps}</p>
            </div>
          </div>
          <span className="text-xs font-mono text-slate-400">
            {Math.round((currentStep / totalSteps) * 100)}% Complete
          </span>
        </div>

        {/* Progress bar line */}
        <div className="w-full h-1.5 bg-navy-800 rounded-full overflow-hidden">
          <motion.div
            className="h-full bg-gradient-to-r from-violet-600 via-indigo-500 to-teal-400"
            initial={{ width: `${((currentStep - 1) / totalSteps) * 100}%` }}
            animate={{ width: `${(currentStep / totalSteps) * 100}%` }}
            transition={{ duration: 0.3 }}
          />
        </div>
      </div>

      {/* ─── Step Content Container ────────────────────────────────────────── */}
      <Card className="p-6 bg-navy-900/90 border-navy-700 shadow-2xl rounded-2xl relative overflow-hidden backdrop-blur-md">
        <AnimatePresence mode="wait">
          {/* STEP 1: BUSINESS & INDUSTRY */}
          {currentStep === 1 && (
            <motion.div
              key="step-1"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              transition={{ duration: 0.2 }}
              className="space-y-5"
            >
              <div>
                <h2 className="text-lg sm:text-xl font-bold text-slate-100 mb-1">
                  What is your business called?
                </h2>
                <p className="text-xs text-slate-400">
                  Your AI assistant will introduce itself on behalf of your business.
                </p>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1.5">
                  Business Name
                </label>
                <input
                  type="text"
                  value={businessName}
                  onChange={(e) => {
                    setBusinessName(e.target.value);
                    if (!assistantName || assistantName === 'Maya') {
                      setAssistantName(`${e.target.value} Assistant`);
                    }
                  }}
                  placeholder="e.g. Dr. Smile Dental Clinic, Apex Realty, Glow Salon"
                  className="w-full bg-navy-950 border border-navy-700 focus:border-violet-500 rounded-xl px-4 py-3 text-sm text-slate-100 placeholder-slate-600 outline-none transition-all shadow-inner"
                  autoFocus
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-2">
                  What type of business is it?
                </label>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2.5">
                  {[
                    { id: 'dental', label: '🦷 Dental Clinic', desc: 'Patients & appointments' },
                    { id: 'real_estate', label: '🏡 Real Estate', desc: 'Buyers, sellers & tours' },
                    { id: 'salon', label: '💇 Hair & Spa', desc: 'Services & stylists' },
                    { id: 'school', label: '🎓 School / Academy', desc: 'Admissions & tours' },
                    { id: 'b2b', label: '💼 B2B & Agency', desc: 'Clients & demos' },
                    { id: 'auto', label: '🚗 Auto Dealership', desc: 'Cars & test drives' },
                  ].map((ind) => (
                    <button
                      key={ind.id}
                      type="button"
                      onClick={() => handleIndustryChange(ind.id as IndustryType)}
                      className={cn(
                        'p-3 rounded-xl border text-left transition-all',
                        industry === ind.id
                          ? 'bg-violet-600/20 border-violet-500 text-white shadow-md shadow-violet-600/10'
                          : 'bg-navy-950/60 border-navy-800 text-slate-400 hover:text-slate-200 hover:border-navy-700'
                      )}
                    >
                      <p className="text-xs font-bold">{ind.label}</p>
                      <p className="text-[10px] text-slate-500 mt-0.5">{ind.desc}</p>
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1.5">
                  Assistant Name (Optional)
                </label>
                <input
                  type="text"
                  value={assistantName}
                  onChange={(e) => setAssistantName(e.target.value)}
                  placeholder="e.g. Maya, Jordan, or Alex"
                  className="w-full bg-navy-950 border border-navy-700 focus:border-violet-500 rounded-xl px-4 py-2.5 text-xs text-slate-100 placeholder-slate-600 outline-none"
                />
              </div>
            </motion.div>
          )}

          {/* STEP 2: PLAIN BUSINESS DESCRIPTION (AI LOGIC GENERATOR) */}
          {currentStep === 2 && (
            <motion.div
              key="step-2"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              transition={{ duration: 0.2 }}
              className="space-y-4"
            >
              <div>
                <h2 className="text-lg sm:text-xl font-bold text-slate-100 mb-1">
                  Describe your business and your ideal customer
                </h2>
                <p className="text-xs text-slate-400">
                  In plain English, tell us what you do, what you sell, and what makes a lead qualified for you. Our AI will automatically write all the questions and rules.
                </p>
              </div>

              <div className="relative">
                <textarea
                  value={businessDescription}
                  onChange={(e) => {
                    setBusinessDescription(e.target.value);
                    setGeneratedSuccess(false);
                  }}
                  rows={4}
                  placeholder="e.g. We are a residential real estate agency in Dallas. Our ideal customers are looking to buy or sell homes with a budget above $350k within the next 90 days. We need to know their timeline, budget, and if they are pre-approved for a mortgage."
                  className="w-full bg-navy-950 border border-navy-700 focus:border-violet-500 rounded-xl p-3.5 text-xs text-slate-100 placeholder-slate-600 outline-none leading-relaxed shadow-inner resize-none"
                />
              </div>

              {/* AI Trigger button */}
              <div className="flex items-center justify-between p-3 rounded-xl bg-violet-950/30 border border-violet-500/30">
                <div className="flex items-center gap-2">
                  <Sparkles className="w-4 h-4 text-violet-400" />
                  <div>
                    <p className="text-xs font-semibold text-slate-200">
                      {generatedSuccess ? 'Qualification Rules Ready' : 'AI Qualification Auto-Builder'}
                    </p>
                    <p className="text-[10px] text-slate-400">
                      {generatedSuccess
                        ? `${qualificationRules.length} questions & ${knowledgeBase.length} FAQ answers generated`
                        : 'Click to build rules automatically from your description'}
                    </p>
                  </div>
                </div>

                <Button
                  size="sm"
                  onClick={handleGenerateRules}
                  loading={isGeneratingRules}
                  className="text-xs font-semibold"
                >
                  {generatedSuccess ? '✨ Re-generate' : '✨ Generate Rules'}
                </Button>
              </div>

              {/* Optional Website Link Helper */}
              <div className="pt-2 border-t border-navy-800 flex flex-col sm:flex-row items-center gap-2">
                <span className="text-[11px] text-slate-400 whitespace-nowrap">Or scan your website:</span>
                <input
                  type="url"
                  value={websiteUrl}
                  onChange={(e) => setWebsiteUrl(e.target.value)}
                  placeholder="https://yourwebsite.com"
                  className="flex-1 bg-navy-950 border border-navy-800 rounded-lg px-3 py-1.5 text-xs text-slate-200 placeholder-slate-600 outline-none"
                />
                <Button
                  size="sm"
                  variant="secondary"
                  onClick={handleScanWebsite}
                  loading={isScanningWebsite}
                  disabled={!websiteUrl.trim() || isScanningWebsite}
                  className="text-xs whitespace-nowrap"
                >
                  Scan Site
                </Button>
              </div>
            </motion.div>
          )}

          {/* STEP 3: CONVERSATION STYLE & VOICE */}
          {currentStep === 3 && (
            <motion.div
              key="step-3"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              transition={{ duration: 0.2 }}
              className="space-y-5"
            >
              <div>
                <h2 className="text-lg sm:text-xl font-bold text-slate-100 mb-1">
                  How should your assistant talk to customers?
                </h2>
                <p className="text-xs text-slate-400">
                  Pick the personality that best reflects your business brand.
                </p>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                {[
                  {
                    id: 'friendly',
                    emoji: '🤝',
                    title: 'Friendly & Caring',
                    desc: 'Warm, reassuring, and patient. Recommended for clinics, salons & schools.',
                  },
                  {
                    id: 'professional',
                    emoji: '💼',
                    title: 'Professional & Crisp',
                    desc: 'Polite, clear, and business-focused. Recommended for B2B & real estate.',
                  },
                  {
                    id: 'casual',
                    emoji: '🌟',
                    title: 'Casual & Upbeat',
                    desc: 'Modern, vibrant, and conversational. Great for trendy salons & studios.',
                  },
                ].map((p) => (
                  <button
                    key={p.id}
                    type="button"
                    onClick={() => setTone(p.id as ToneType)}
                    className={cn(
                      'p-4 rounded-xl border text-left transition-all flex flex-col justify-between',
                      tone === p.id
                        ? 'bg-violet-600/20 border-violet-500 text-white shadow-lg shadow-violet-600/15'
                        : 'bg-navy-950/60 border-navy-800 text-slate-400 hover:text-slate-200'
                    )}
                  >
                    <div>
                      <span className="text-2xl mb-2 block">{p.emoji}</span>
                      <p className="text-xs font-bold text-slate-100 mb-1">{p.title}</p>
                      <p className="text-[11px] text-slate-400 leading-relaxed">{p.desc}</p>
                    </div>
                    {tone === p.id && (
                      <span className="mt-3 text-[10px] text-violet-400 font-semibold flex items-center gap-1">
                        <Check className="w-3 h-3" /> Selected
                      </span>
                    )}
                  </button>
                ))}
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-2">
                  Use Emojis in Messages?
                </label>
                <div className="grid grid-cols-3 gap-2.5">
                  {[
                    { id: 'subtle', label: '👍 Subtle', desc: '1-2 emojis per chat (recommended)' },
                    { id: 'expressive', label: '✨ Expressive', desc: 'Lively & colorful emojis' },
                    { id: 'none', label: '🚫 None', desc: 'Strict plain text only' },
                  ].map((em) => (
                    <button
                      key={em.id}
                      type="button"
                      onClick={() => setEmojiStyle(em.id as EmojiStyle)}
                      className={cn(
                        'p-2.5 rounded-xl border text-left transition-all',
                        emojiStyle === em.id
                          ? 'bg-violet-600/15 border-violet-500 text-violet-300'
                          : 'bg-navy-950/60 border-navy-800 text-slate-400 hover:text-slate-200'
                      )}
                    >
                      <p className="text-xs font-bold">{em.label}</p>
                      <p className="text-[10px] text-slate-500">{em.desc}</p>
                    </button>
                  ))}
                </div>
              </div>
            </motion.div>
          )}

          {/* STEP 4: FOLLOW-UP PERSISTENCE & CUSTOMIZER */}
          {currentStep === 4 && (
            <motion.div
              key="step-4"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              transition={{ duration: 0.2 }}
              className="space-y-5"
            >
              <div>
                <h2 className="text-lg sm:text-xl font-bold text-slate-100 mb-1">
                  How persistent should follow-ups be?
                </h2>
                <p className="text-xs text-slate-400">
                  If a customer goes silent midway through a conversation, choose when and what your assistant sends to re-engage them.
                </p>
              </div>

              {/* 3 Quick Presets */}
              <div className="grid grid-cols-1 gap-2.5">
                {[
                  {
                    id: 'gentle',
                    icon: '🍃',
                    title: 'Gentle',
                    badge: 'Relaxed & Polite',
                    desc: 'Sends 1 reminder after 2 days, and 1 final friendly check-in after 1 week.',
                    cadencePills: ['1st: After 2 days', '2nd: After 7 days'],
                  },
                  {
                    id: 'balanced',
                    icon: '⚖️',
                    title: 'Balanced (Recommended)',
                    badge: 'Best Conversion',
                    desc: 'Sends 1 check-in after 24 hours, 1 after 3 days, and 1 final follow-up after 7 days.',
                    cadencePills: ['1st: After 24 hrs', '2nd: After 3 days', '3rd: After 7 days'],
                  },
                  {
                    id: 'aggressive',
                    icon: '🚀',
                    title: 'Aggressive',
                    badge: 'Fast Sales Pipeline',
                    desc: 'Sends 1 check-in after 2 hours, 1 after 24 hours, and 1 after 3 days. Best for high-intent inquiries.',
                    cadencePills: ['1st: After 2 hrs', '2nd: After 24 hrs', '3rd: After 3 days'],
                  },
                ].map((c) => {
                  const isSelected = followupCadence === c.id && !isCustomFollowup;
                  return (
                    <button
                      key={c.id}
                      type="button"
                      onClick={() => handleSelectCadencePreset(c.id as any)}
                      className={cn(
                        'w-full p-3.5 rounded-xl border text-left transition-all flex items-start gap-3.5 relative overflow-hidden',
                        isSelected
                          ? 'bg-violet-600/20 border-violet-500 text-white shadow-md shadow-violet-600/10'
                          : 'bg-navy-950/60 border-navy-800 text-slate-400 hover:text-slate-200 hover:border-navy-700'
                      )}
                    >
                      <span className="text-2xl mt-0.5">{c.icon}</span>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between mb-1">
                          <p className="text-xs font-bold text-slate-100 flex items-center gap-2">
                            {c.title}
                            {isSelected && (
                              <span className="text-[10px] text-violet-400 font-semibold flex items-center gap-1">
                                <Check className="w-3 h-3" /> Active
                              </span>
                            )}
                          </p>
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-navy-850 text-slate-300 border border-navy-700">
                            {c.badge}
                          </span>
                        </div>
                        <p className="text-xs text-slate-400 mb-2 leading-relaxed">{c.desc}</p>
                        
                        {/* Cadence Pills */}
                        <div className="flex flex-wrap items-center gap-1.5">
                          {c.cadencePills.map((pill, idx) => (
                            <span
                              key={idx}
                              className={cn(
                                'text-[10px] px-2 py-0.5 rounded-md font-mono',
                                isSelected
                                  ? 'bg-violet-500/20 text-violet-300 border border-violet-500/30'
                                  : 'bg-navy-900 text-slate-400 border border-navy-800'
                              )}
                            >
                              {pill}
                            </span>
                          ))}
                        </div>
                      </div>
                    </button>
                  );
                })}
              </div>

              {/* Customizer Expandable Section */}
              <div className="border border-navy-700/80 bg-navy-950/90 rounded-2xl p-4 space-y-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2.5">
                    <div className="w-8 h-8 rounded-xl bg-violet-600/20 border border-violet-500/30 flex items-center justify-center text-violet-400">
                      <Sliders className="w-4 h-4" />
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <p className="text-xs font-bold text-slate-200">Custom Sequence Builder</p>
                        {isCustomFollowup && (
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-violet-600/30 text-violet-300 border border-violet-500/40 font-semibold">
                            Custom Active ({followupSteps.length} steps)
                          </span>
                        )}
                      </div>
                      <p className="text-[11px] text-slate-400">
                        Tune individual message delays, text wording, and smart variables.
                      </p>
                    </div>
                  </div>

                  <Button
                    type="button"
                    variant="secondary"
                    size="sm"
                    onClick={() => setIsCustomFollowup(!isCustomFollowup)}
                    className="text-xs flex items-center gap-1.5"
                  >
                    {isCustomFollowup ? (
                      <>
                        <ChevronUp className="w-3.5 h-3.5" /> Hide Custom Editor
                      </>
                    ) : (
                      <>
                        <Sliders className="w-3.5 h-3.5" /> Customize Messages
                      </>
                    )}
                  </Button>
                </div>

                {isCustomFollowup && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    exit={{ opacity: 0, height: 0 }}
                    transition={{ duration: 0.25 }}
                    className="space-y-4 pt-3 border-t border-navy-800"
                  >
                    {/* Step by Step List */}
                    <div className="space-y-3">
                      {followupSteps.map((step, idx) => (
                        <div
                          key={step.id || idx}
                          className="p-3.5 rounded-xl bg-navy-900 border border-navy-800 space-y-2.5 relative"
                        >
                          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-2 border-b border-navy-800">
                            <div className="flex items-center gap-2">
                              <span className="w-5 h-5 rounded-full bg-violet-600/30 border border-violet-500/50 text-violet-300 text-[10px] font-bold flex items-center justify-center">
                                {idx + 1}
                              </span>
                              <span className="text-xs font-bold text-slate-200">
                                Follow-up #{idx + 1}
                              </span>
                            </div>

                            {/* Delay Selector */}
                            <div className="flex items-center gap-2">
                              <span className="text-[11px] text-slate-400 flex items-center gap-1">
                                <Clock className="w-3 h-3 text-slate-500" /> Send after:
                              </span>
                              <select
                                value={step.delayHours}
                                onChange={(e) => {
                                  const hours = parseFloat(e.target.value);
                                  const matched = DELAY_OPTIONS.find((o) => o.hours === hours);
                                  handleUpdateFollowupStep(idx, {
                                    delayHours: hours,
                                    delayLabel: matched?.label || `${hours} hours`,
                                  });
                                }}
                                className="bg-navy-950 border border-navy-700 text-slate-200 text-xs rounded-lg px-2.5 py-1 outline-none focus:border-violet-500"
                              >
                                {DELAY_OPTIONS.map((opt) => (
                                  <option key={opt.hours} value={opt.hours}>
                                    {opt.label}
                                  </option>
                                ))}
                              </select>

                              {followupSteps.length > 1 && (
                                <button
                                  type="button"
                                  onClick={() => handleRemoveFollowupStep(idx)}
                                  className="p-1 text-slate-500 hover:text-red-400 transition-colors ml-1"
                                  title="Delete this follow-up"
                                >
                                  <Trash2 className="w-3.5 h-3.5" />
                                </button>
                              )}
                            </div>
                          </div>

                          {/* Message Template Textarea */}
                          <div>
                            <textarea
                              value={step.template}
                              onChange={(e) => handleUpdateFollowupStep(idx, { template: e.target.value })}
                              rows={2}
                              placeholder="Type your follow-up message..."
                              className="w-full bg-navy-950 border border-navy-800 rounded-lg p-2.5 text-xs text-slate-200 placeholder-slate-600 outline-none focus:border-violet-500 resize-none leading-relaxed"
                            />
                            
                            {/* Insertable variable tags */}
                            <div className="flex flex-wrap items-center gap-1.5 mt-1.5">
                              <span className="text-[10px] text-slate-500">Insert tag:</span>
                              {[
                                { tag: '{name}', label: 'Customer Name' },
                                { tag: '{business}', label: 'Business Name' },
                                { tag: '{booking_url}', label: 'Booking Link' },
                              ].map((v) => (
                                <button
                                  key={v.tag}
                                  type="button"
                                  onClick={() => handleInsertVariable(idx, v.tag)}
                                  className="text-[10px] font-mono px-2 py-0.5 rounded-md bg-navy-800 border border-navy-700 text-violet-300 hover:bg-violet-600/20 hover:border-violet-500/40 transition-colors"
                                >
                                  +{v.tag}
                                </button>
                              ))}
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* Add Step & Reset Buttons */}
                    <div className="flex flex-col sm:flex-row items-center justify-between gap-2 pt-1">
                      {followupSteps.length < 5 ? (
                        <button
                          type="button"
                          onClick={handleAddFollowupStep}
                          className="w-full sm:w-auto px-4 py-2 rounded-xl border border-dashed border-violet-500/40 hover:border-violet-400 bg-violet-600/10 hover:bg-violet-600/20 text-violet-300 text-xs font-semibold flex items-center justify-center gap-1.5 transition-all"
                        >
                          <Plus className="w-3.5 h-3.5" /> Add Another Follow-up (Max 5)
                        </button>
                      ) : (
                        <span className="text-[11px] text-slate-500 italic">
                          Maximum 5 follow-up attempts reached.
                        </span>
                      )}

                      <button
                        type="button"
                        onClick={handleResetToPreset}
                        className="text-xs text-slate-400 hover:text-slate-200 flex items-center gap-1 transition-colors"
                      >
                        <RotateCcw className="w-3 h-3" /> Reset to preset defaults
                      </button>
                    </div>

                    {/* Automation Guardrails */}
                    <div className="p-3.5 rounded-xl bg-navy-900/60 border border-navy-800/80 space-y-2.5 mt-3">
                      <p className="text-[11px] font-bold text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
                        <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                        Automation Safety Guardrails
                      </p>

                      <div className="space-y-2 text-xs">
                        <label className="flex items-center gap-2.5 cursor-pointer text-slate-300 hover:text-slate-100">
                          <input
                            type="checkbox"
                            checked={stopOnReply}
                            onChange={(e) => setStopOnReply(e.target.checked)}
                            className="w-4 h-4 rounded bg-navy-950 border-navy-700 text-violet-600 focus:ring-violet-500"
                          />
                          <span>
                            <strong>Stop automatically on reply:</strong> Cancel remaining messages as soon as the lead answers.
                          </span>
                        </label>

                        <label className="flex items-center gap-2.5 cursor-pointer text-slate-300 hover:text-slate-100">
                          <input
                            type="checkbox"
                            checked={stopOnBooking}
                            onChange={(e) => setStopOnBooking(e.target.checked)}
                            className="w-4 h-4 rounded bg-navy-950 border-navy-700 text-violet-600 focus:ring-violet-500"
                          />
                          <span>
                            <strong>Stop on appointment booked:</strong> Cancel follow-ups once a time slot is reserved.
                          </span>
                        </label>

                        <label className="flex items-center gap-2.5 cursor-pointer text-slate-300 hover:text-slate-100">
                          <input
                            type="checkbox"
                            checked={onlyBusinessHours}
                            onChange={(e) => setOnlyBusinessHours(e.target.checked)}
                            className="w-4 h-4 rounded bg-navy-950 border-navy-700 text-violet-600 focus:ring-violet-500"
                          />
                          <span>
                            <strong>Business hours only (9 AM – 8 PM):</strong> Prevent late-night WhatsApp notifications.
                          </span>
                        </label>
                      </div>
                    </div>
                  </motion.div>
                )}
              </div>
            </motion.div>
          )}

          {/* STEP 5: BOOKING & APPOINTMENTS */}
          {currentStep === 5 && (
            <motion.div
              key="step-5"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              transition={{ duration: 0.2 }}
              className="space-y-5"
            >
              <div>
                <h2 className="text-lg sm:text-xl font-bold text-slate-100 mb-1">
                  Where should qualified customers book with you?
                </h2>
                <p className="text-xs text-slate-400">
                  When a customer qualifies as a great lead, your assistant will send them this link to schedule a time.
                </p>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1.5">
                  Your Booking Link (Calendly, Cal.com, or Website)
                </label>
                <div className="relative">
                  <input
                    type="url"
                    value={bookingUrl}
                    onChange={(e) => setBookingUrl(e.target.value)}
                    placeholder="https://calendly.com/your-business/consultation"
                    className="w-full bg-navy-950 border border-navy-700 focus:border-violet-500 rounded-xl px-4 py-3 text-xs text-slate-100 placeholder-slate-600 outline-none"
                  />
                </div>
                <p className="text-[11px] text-slate-500 mt-1.5">
                  💡 Don't have a link? Leave blank and your assistant will collect their preferred time directly in WhatsApp.
                </p>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-2">
                  Appointment Duration
                </label>
                <div className="grid grid-cols-4 gap-2.5">
                  {[15, 30, 45, 60].map((mins) => (
                    <button
                      key={mins}
                      type="button"
                      onClick={() => setMeetingDuration(mins)}
                      className={cn(
                        'py-2.5 rounded-xl border text-center font-bold text-xs transition-all',
                        meetingDuration === mins
                          ? 'bg-violet-600/20 border-violet-500 text-violet-300'
                          : 'bg-navy-950/60 border-navy-800 text-slate-400 hover:text-slate-200'
                      )}
                    >
                      {mins} mins
                    </button>
                  ))}
                </div>
              </div>
            </motion.div>
          )}

          {/* STEP 6: CONNECT WHATSAPP (GUIDED QR CODE) */}
          {currentStep === 6 && (
            <motion.div
              key="step-6"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              transition={{ duration: 0.2 }}
              className="space-y-5"
            >
              <div>
                <h2 className="text-lg sm:text-xl font-bold text-slate-100 mb-1">
                  Connect your WhatsApp in 10 seconds
                </h2>
                <p className="text-xs text-slate-400">
                  No technical keys or developer setup needed. Just scan the code with your phone.
                </p>
              </div>

              {whatsappState === 'connected' ? (
                <div className="p-6 rounded-2xl bg-emerald-500/10 border border-emerald-500/30 text-center space-y-2">
                  <div className="w-12 h-12 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center mx-auto">
                    <Check className="w-6 h-6" />
                  </div>
                  <p className="text-sm font-bold text-emerald-300">WhatsApp is Connected!</p>
                  <p className="text-xs text-slate-400 font-mono">{connectedNumber}</p>
                </div>
              ) : (
                <div className="p-5 rounded-2xl bg-navy-950 border border-navy-800 flex flex-col sm:flex-row items-center gap-6">
                  {/* Left: QR Display */}
                  <div className="w-44 h-44 rounded-xl bg-white p-2 flex items-center justify-center shadow-md flex-shrink-0">
                    {isLoadingQr ? (
                      <div className="flex flex-col items-center gap-2 text-slate-800">
                        <Loader2 className="w-6 h-6 animate-spin text-violet-600" />
                        <span className="text-[10px] font-semibold">Generating QR...</span>
                      </div>
                    ) : qrCode ? (
                      <img src={qrCode} alt="WhatsApp QR Code" className="w-full h-full object-contain" />
                    ) : (
                      <div className="text-center p-2">
                        <QrCode className="w-10 h-10 text-slate-400 mx-auto mb-1.5" />
                        <button
                          onClick={handleFetchQr}
                          className="text-[11px] font-bold text-violet-600 hover:underline"
                        >
                          Click to Generate QR Code
                        </button>
                      </div>
                    )}
                  </div>

                  {/* Right: Plain steps */}
                  <div className="space-y-2.5 text-xs text-slate-300">
                    <p className="font-bold text-slate-100 text-sm">How to link:</p>
                    <div className="flex items-start gap-2">
                      <span className="w-5 h-5 rounded-full bg-navy-800 text-violet-400 flex items-center justify-center font-bold text-[10px] flex-shrink-0">
                        1
                      </span>
                      <span>Open WhatsApp on your phone</span>
                    </div>
                    <div className="flex items-start gap-2">
                      <span className="w-5 h-5 rounded-full bg-navy-800 text-violet-400 flex items-center justify-center font-bold text-[10px] flex-shrink-0">
                        2
                      </span>
                      <span>Tap <strong>Settings</strong> (or ⋮) ➔ <strong>Linked Devices</strong></span>
                    </div>
                    <div className="flex items-start gap-2">
                      <span className="w-5 h-5 rounded-full bg-navy-800 text-violet-400 flex items-center justify-center font-bold text-[10px] flex-shrink-0">
                        3
                      </span>
                      <span>Tap <strong>Link a Device</strong> and scan this code</span>
                    </div>

                    {!qrCode && (
                      <Button size="sm" onClick={handleFetchQr} loading={isLoadingQr} className="mt-2 w-full text-xs">
                        Generate QR Code
                      </Button>
                    )}
                  </div>
                </div>
              )}

              {/* Advanced Settings Toggle */}
              <div className="pt-2 border-t border-navy-800">
                <button
                  type="button"
                  onClick={() => setShowAdvanced(!showAdvanced)}
                  className="flex items-center justify-between w-full text-xs text-slate-400 hover:text-slate-200 py-1"
                >
                  <span className="flex items-center gap-1.5 font-medium">
                    <Settings className="w-3.5 h-3.5" /> Advanced Settings (for fine-tuning raw numbers)
                  </span>
                  {showAdvanced ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                </button>

                {showAdvanced && (
                  <div className="mt-3 p-4 rounded-xl bg-navy-950 border border-navy-800 space-y-3">
                    <div className="grid grid-cols-2 gap-3">
                      <div>
                        <label className="block text-[11px] text-slate-400 mb-1">Hot Lead Score Threshold</label>
                        <input
                          type="number"
                          value={hotThreshold}
                          onChange={(e) => setHotThreshold(+e.target.value)}
                          className="w-full bg-navy-900 border border-navy-700 rounded-lg px-2.5 py-1.5 text-xs text-slate-100"
                        />
                      </div>
                      <div>
                        <label className="block text-[11px] text-slate-400 mb-1">Warm Lead Threshold</label>
                        <input
                          type="number"
                          value={warmThreshold}
                          onChange={(e) => setWarmThreshold(+e.target.value)}
                          className="w-full bg-navy-900 border border-navy-700 rounded-lg px-2.5 py-1.5 text-xs text-slate-100"
                        />
                      </div>
                    </div>

                    <div>
                      <label className="block text-[11px] text-slate-400 mb-1">Custom System Instructions (Optional Override)</label>
                      <textarea
                        value={customPrompt}
                        onChange={(e) => setCustomPrompt(e.target.value)}
                        placeholder="e.g. Always mention we offer 0% interest financing for 12 months..."
                        rows={2}
                        className="w-full bg-navy-900 border border-navy-700 rounded-lg p-2 text-xs text-slate-100 placeholder-slate-600 resize-none"
                      />
                    </div>

                    <div>
                      <label className="block text-[11px] text-slate-400 mb-1">Outbound Webhook URL (Zapier / Make)</label>
                      <input
                        type="url"
                        value={webhookUrl}
                        onChange={(e) => setWebhookUrl(e.target.value)}
                        placeholder="https://hooks.zapier.com/..."
                        className="w-full bg-navy-900 border border-navy-700 rounded-lg px-2.5 py-1.5 text-xs text-slate-100"
                      />
                    </div>
                  </div>
                )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* ─── Footer Navigation Buttons ───────────────────────────────────── */}
        <div className="flex items-center justify-between pt-6 mt-6 border-t border-navy-800">
          {currentStep > 1 ? (
            <Button variant="secondary" size="sm" onClick={handleBack} className="text-xs">
              <ArrowLeft className="w-3.5 h-3.5 mr-1" /> Back
            </Button>
          ) : (
            <div />
          )}

          <Button
            size="sm"
            onClick={handleNext}
            loading={isSavingAll}
            className="px-6 text-xs font-semibold bg-violet-600 hover:bg-violet-500 shadow-lg shadow-violet-600/20"
          >
            {currentStep === totalSteps ? 'Complete & Launch 🚀' : 'Next Step'}
            {currentStep < totalSteps && <ArrowRight className="w-3.5 h-3.5 ml-1" />}
          </Button>
        </div>
      </Card>
    </div>
  );
}
